Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v|
      v.memory = 2048
    end
    config.vm.define "tag_cloud" do |cloudru|
      cloudru.vm.box = "generic/ubuntu2204"
      cloudru.vm.hostname = "server"
      cloudru.vm.network :private_network, ip: "192.168.56.20"
      cloudru.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        base_path = File.dirname(__FILE__)
        dynamic_path = File.join(base_path, "environments", "cloud_ru", "group_vars", "variables.yml")
        ansible.playbook = "playbook.yml"
        ansible.groups = {
          "cloudru" => ["tag_cloud"],
        }
        ansible.extra_vars = dynamic_path
        
      end
    end
  end
