apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: cloudru
  labels:
    app: web-app
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: web-app
